ruby_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :resources do
    get 'prev_button', to: 'resources:prev_button', as: 'prev_button'
    get 'next_button', to: 'resources:next_button', as: 'next_button'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

ruby_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby_app/app/models/pdf.rb
class Pdf < ApplicationRecord
  has_one_attached :pfile
end

ruby_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def next
    cookies[:ID] = cookies[:ID] + 1
    if cookies[:ID] == Pdf.count()
      cookies[:ID] = 0
    end
  end
  def prev
    cookies[:ID] = cookies[:ID] - 1
    if cookies[:ID] == -1
      cookies[:ID] = Pdf.count()
    end
  end
end

ruby_app/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def next_button
    session[:ID] = session[:ID] + 1
    if session[:ID] == Pdf.count()
      session[:ID] = 0
    end
    iid = session[:ID]
    @pdf = Pdf.where(id: iid).first!
    if (@pdf.process_time == "0")
      path = @pdf.pfile.blob.key
      system("python3 algo/algo.py " + path)
      while Dir.exist?('storage/' + path[0] + path[1] + '/' + path[2] + path[3] + '/FIN')
        sleep 1
      end
      @pdf.process_time = "1"
      @pdf.save!
    end
    redirect_to "/"
  end
  def prev_button
    session[:ID] = session[:ID] - 1
    if session[:ID] == -1
      session[:ID] = Pdf.count() - 1
    end
    iid = session[:ID]
    @pdf = Pdf.where(id: iid).first!
    if (@pdf.process_time == "0")
      path = @pdf.pfile.blob.key
      system("python3 algo/algo.py " + path)
      while Dir.exist?('storage/' + path[0] + path[1] + '/' + path[2] + path[3] + '/FIN')
        sleep 1
      end
      @pdf.process_time = "1"
      @pdf.save!
    end
    redirect_to "/"
  end
end

ruby_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_app/app/helpers/home_helper.rb
module HomeHelper
end

ruby_app/app/views/home/index.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<% if session[:ID].nil?  %>
<% session[:ID] = 0 %>
<% end %>
<% iid = session[:ID] %>
<% @pdf = Pdf.where(id: iid).first! %>
<div id="wrapper">
  <div id="first">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Title</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse show" id="navbarColor01" style="">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">Title: <%= p @pdf.title %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Page Count: <%= p @pdf.page_count %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Process Time: <%= p @pdf.process_time %></a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
          <div class="btn-group justify-content-center btn-block" role="button group" aria-label="document nav">
            <%= link_to('<button id="previousButton" type="button" class="btn btn-secondary prev1">Previous</button>'.html_safe, resources_prev_button_path, method: :post) %>
            <%= link_to('<button id="nextButton" type="button" class="btn btn-secondary">Next</button>'.html_safe, resources_next_button_path, method: :post) %>
          </div>
          <button type="button" class="btn btn-success btn-block">Generate Sample</button>
        </div>
      </div>
    </nav>
</div>
<div id="second">
<iframe src="<%= rails_blob_path(@pdf.pfile, disposition: :inline) %>" class="col py-3" style="width: 400%; height: 98vh;"></iframe>
</div>

ruby_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>B0unding B0x</title>
    <!-- Provide proper viewport information so that the layout works on mobile devices. -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<style>
.navbar .container-fluid, .navbar-expand-lg .navbar-collapse, .navbar .navbar-nav{
  flex-direction: column;
  align-items: flex-start;
}
.navbar{
  width:auto;
  height:100vh;
  align-items: flex-start;
}
.btn-group{
  margin-top: 0.5rem;
  width: 100%
}
.btn-group .btn
{
  width: 50%;
}
#wrapper {
  flex:100%;
  /*width: 400px;
  /*overflow: hidden; /* will contain if #first is longer than #second */
}
#first {
  /*flex:auto;*/
  width: 350px;
  float: left; /* add this */
}
#second {
  overflow: hidden; /* if you don't want #second to wrap below #first */
}
</style>